### ISSUE TITLE
Update the screenshots of the app in readme

### ISSUE THREAD

**Issue by rob729** [rob729/Minimal_ToDo#11]
**Describe the chore**
Currently, the images in the readme are of the older version of the app. Updates the screenshots present in the readme.

**Additional Context**
Link of the screenshots to be added: https://photos.google.com/share/AF1QipOPqafBSDWt2ijQ91Fwd1o9O72fDLjhTaks3zg-xZ-7jRxXWd6Eep3evU6dNnjOHQ?key=T1RqSlJiMDlGbExSaURnaHVEbTlEWWxFaWhzMlFn

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by gunisha30** [comment]
> **Describe the chore**
> Currently, the images in the readme are of the older version of the app. Updates the screenshots present in the readme.
> 
> **Additional Context**
> Link of the screenshots to be added: https://photos.google.com/share/AF1QipOPqafBSDWt2ijQ91Fwd1o9O72fDLjhTaks3zg-xZ-7jRxXWd6Eep3evU6dNnjOHQ?key=T1RqSlJiMDlGbExSaURnaHVEbTlEWWxFaWhzMlFn
> 
> **Would you like to work on the issue?**
> 
> * [ ]  Yes
> * [ ]  No
> * Other: Open for all

I would like to work on this.

**Comment by rob729** [comment]
@gunisha30 Their is an already existing open PR on this. You can work on other issues.
